// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYVM2lR1ceQLIEgoeIl4mabn2_KpTDLMc',
    appId: '1:240336290070:web:a06cde453e46874dcd1037',
    messagingSenderId: '240336290070',
    projectId: 'sanad-1437c',
    authDomain: 'sanad-1437c.firebaseapp.com',
    databaseURL: 'https://sanad-1437c-default-rtdb.firebaseio.com',
    storageBucket: 'sanad-1437c.firebasestorage.app',
    measurementId: 'G-J45VKFMHRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUCMq3uLRWQiJjGWZvwS0sjaz7L3m30W8',
    appId: '1:240336290070:android:ede3cc2f8982bad2cd1037',
    messagingSenderId: '240336290070',
    projectId: 'sanad-1437c',
    databaseURL: 'https://sanad-1437c-default-rtdb.firebaseio.com',
    storageBucket: 'sanad-1437c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8hJGSbYg0KsP2jIVbfke_N9uoptuEwU',
    appId: '1:240336290070:ios:4d40f6a63add92c7cd1037',
    messagingSenderId: '240336290070',
    projectId: 'sanad-1437c',
    databaseURL: 'https://sanad-1437c-default-rtdb.firebaseio.com',
    storageBucket: 'sanad-1437c.firebasestorage.app',
    iosClientId: '240336290070-0jqlhn66qjrnjdc7rt7p2g0b67ebs66j.apps.googleusercontent.com',
    iosBundleId: 'sanad.com.sanadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv8hJGSbYg0KsP2jIVbfke_N9uoptuEwU',
    appId: '1:240336290070:ios:4d40f6a63add92c7cd1037',
    messagingSenderId: '240336290070',
    projectId: 'sanad-1437c',
    databaseURL: 'https://sanad-1437c-default-rtdb.firebaseio.com',
    storageBucket: 'sanad-1437c.firebasestorage.app',
    iosClientId: '240336290070-0jqlhn66qjrnjdc7rt7p2g0b67ebs66j.apps.googleusercontent.com',
    iosBundleId: 'sanad.com.sanadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYVM2lR1ceQLIEgoeIl4mabn2_KpTDLMc',
    appId: '1:240336290070:web:790921ba6b277977cd1037',
    messagingSenderId: '240336290070',
    projectId: 'sanad-1437c',
    authDomain: 'sanad-1437c.firebaseapp.com',
    databaseURL: 'https://sanad-1437c-default-rtdb.firebaseio.com',
    storageBucket: 'sanad-1437c.firebasestorage.app',
    measurementId: 'G-Y8NJEGLRBD',
  );
}
